### PR TITLE
changed much too to too much in README.md

### PR DESCRIPTION
**Pull request by Krrishdhaneja**

### CODE REVIEW

**Comment by fm-sys** [comment]
Are you sure about this one? To me it sounds a bit strange, but I'm not an English Native... 🤷‍♂️

**Comment by Krrishdhaneja** [comment]
> Are you sure about this one? To me it sounds a bit strange, but I'm not an English Native... 🤷‍♂️

Umm.. so I think the phrase now becomes "too much cumbersome and slow", wouldn't it be sounding better than "Much too cumbersome and slow"? What's your suggestion?

**Comment by fm-sys** [comment]
Maybe you are right. Let's merge...

**Comment by Krrishdhaneja** [comment]
> Maybe you are right. Let's merge... 

Okk

**Comment by Krrishdhaneja** [comment]
Hey Florian, I was wondering if I can sync your repo with my fork, cuz the last time I had to delete the full repo and re-fork it in order to get the changes, do you know any way of syncing it, or i'll have to re-fork it after a change?

**Comment by fm-sys** [comment]
If you are using the github web UI, you could create a PR from the original repo to your fork. Otherwise [this post](https://stackoverflow.com/a/7244456/13513639) might help you...

**Comment by Krrishdhaneja** [comment]
> If you are using the github web UI, you could create a PR from the original repo to your fork.

Umm.. so you have to submit a PR, or I have to?

**Comment by fm-sys** [comment]
You can do that yourself:


https://user-images.githubusercontent.com/64581222/114663762-19e38e80-9cfb-11eb-91b2-2c4b4492c229.mp4

**Comment by Krrishdhaneja** [comment]
> You can do that yourself:
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/64581222/114663762-19e38e80-9cfb-11eb-91b2-2c4b4492c229.mp4
> 
> 
> 
> 

Thanks!

**Pull request merged**
