### PR TITLE
Notification runtime permission

### LINKED ISSUE #251: Re-enable notifications on Android 13+
### Android version

13+

### Describe the bug

We need to ask for user permission to send notifications

### PR DESCRIPTION
**Pull request by sivasubramaniamv**
Fixes #251 

Tested on Realme Narzo 30 5G running Android 13

### CODE REVIEW

**Comment by siva-subramaniam-v** [comment]
@fm-sys I've done basic permission handling and skipped redirecting the user to the app settings after permission has been denied twice(as the user may find it annoying to see a snackbar every time they open the app).

Please take a look and let me know if any changes/improvements are to be made.

**Comment by siva-subramaniam-v** [comment]
- directly ask for the permission as soon as the first download is complete, and show the alert dialog only if permission gets denied

I think this is the appropriate way.

**Comment by fm-sys** [comment]
> "Show the alert dialog only if permission gets denied" - do you want the alert dialog to be shown when shouldShowRequestPermissionRationale() returns true or as soon as the user denies the permission for the first time?

Both options would make sense and are probably pretty equivalent. Or did I missed something?

> "As soon as the first download is complete" - after the first file transfer is complete or after the first file is downloaded? 

As soon as we try to show the first notification, I guess. 

> > directly ask for the permission as soon as the first download is complete, and show the alert dialog only if permission gets denied
> 
> 
> I think this is the appropriate way

OTOH really popular apps like WhatsApp or Signal messager also show the Explanation Dialog before requesting the permission for the first time. IMHO there are good reasons for it...

**Comment by siva-subramaniam-v** [comment]
> Both options would make sense and are probably pretty equivalent. Or did I miss something?

If we implement permission handling as suggested in the [official Android documentation](https://developer.android.com/training/permissions/requesting#java),

1. Showing the alert dialog when the user denies permission (in the permission launcher result callback) will cause the dialog to be shown as soon as the user presses "don't allow".
2. Showing the alert dialog when shouldShowRequestPermissionRationale() returns true will show the dialog only when the action is performed again (ie: In this case, the action is making a file transfer).

> As soon as we try to show the first notification, I guess.

A notification is created for every successfully downloaded file.

If we should show the dialog *as soon as we try to show the first notification*, we'd have to put it in a method that is called when the **file-received** event is fired, which would spawn multiple alert dialogs.

> OTOH really popular apps like WhatsApp or Signal messager also show the Explanation Dialog before requesting the permission for the first time. IMHO there are good reasons for it.

Sounds reasonable.

**Review by KATHLOY-0709 — COMMENTED** [review]
Help me to use

**Pull request closed without merging**
