### PR TITLE
Custom save location

### LINKED ISSUE #93: Custom save location
The default location for Snapdrop is `Download`. But as a user, it is better if I can select a custom directory to save downloaded files, e.g. `Video`, `Received`, or `Snapdrop`. I don't want to mix `Download`'s content with the files downloaded from Chrome, Firefox, etc. I hope this feature will be added to Snapdrop settings. BTW, it could be easier on scoped storage if you use [`SimpleStorageHelper`](https://github.com/anggrayudi/SimpleStorage#simplestoragehelper) to pick the save location.

### PR DESCRIPTION
**Pull request by anggrayudi**
Resolve #93

**Test Results**

device-2021-07-22-004130

Screen Shot 2021-07-22 at 00 40 54

### CODE REVIEW

**Comment by fm-sys** [comment]
Thanks for the contribution!

BTW, Codacy seems to be a bit confused. 😅 I think the problem is that the import statements should be sorted alphabetically But don't care too much about Codacy. Don't get me wrong, I think a consistent coding style is very important in general. (That's why we have codacy ;)) But imports are IMHO not worth to spend too much time for endless reformatting of import orders. I will take a look if I can disable the import order check in codacy...

**Comment by fm-sys** [comment]
I just tested the debug Apk. Yes, it works but the workflow seems not really straight forward:

Screenshot_20210721_205522
Screenshot_20210721_205539


Any ideas how you could optimize this in your library? For other apps which are using SAF this seems to be not necessary. Why is it still necessary in this case?

**Comment by anggrayudi** [comment]
Requesting the root path is a necessary step for Android 10 only. It will be requested once, to grant the storage access. For Android 11+ or Android 9-, it is unnecessary. We have no other way. @fm-sys

**Comment by anggrayudi** [comment]
I have made the wording clearer. If you're ok with this change, then I'll release storage version `0.11.1`

Screen Shot 2021-07-22 at 12 18 01

**Comment by fm-sys** [comment]
> I have made the wording clearer. If you're ok with this change, then I'll release storage version `0.11.1`
> 
> Screen Shot 2021-07-22 at 12 18 01

Yes, that seems way more logical to me, instead of asking "do you want to select this folder anyway?".

One question out of interest: Is the selected directory saved in background, or does the user need to grant access to his folder again after granting general storage permission?

If it is stored in background, the wording should contain something like "Your selected folder will automatically be applied afterwards"...

**Comment by anggrayudi** [comment]
> Is the selected directory saved in background, or does the user need to grant access to his folder again after granting general storage permission?

The access will be remembered, and selecting the root path is only required once.

After the user granted the root access, it will reopen the folder picker and show a toast message, "Now you can select any folders under /storage/emulated/0". IMHO, this message is clear enough.

**Comment by fm-sys** [comment]
Sounds good. So go from my side for `0.11.1` ;-)

**Comment by anggrayudi** [comment]
Updated to `0.11.1`.
Can you check the Codacy, @fm-sys ?

**Comment by fm-sys** [comment]
> Can you check the Codacy, @fm-sys ?

Hm, didn't found a way to disable the check yet. But if the PR is ready from your side I would be fine with merging it...

**Comment by anggrayudi** [comment]
Yes, it is ready from my side, @fm-sys

**Comment by fm-sys** [comment]
Ok, then let's merge 👍

**Pull request merged**
